import ParentProvider from '@/components/shared/ParentProvider'
import { lato, lora, poppins, quickSand, roboto } from '@/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "react-responsive-carousel/lib/styles/carousel.min.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${quickSand.variable} ${lora.variable} ${lato.variable} ${roboto.variable} ${poppins.variable}`}
      >
        <ParentProvider>{children}</ParentProvider>
      </body>
    </html>
  )
}
